export const API_URLS = {
    drivers: "/customusers/",
    cars: "/cars/",
    vans: "/furgon/",
    delivery: "/Delivery/",
    service: "/service/",
    texnic: "/texnic/",
    rays: "/rays/",
    history: "/rayshistory/",
    optol: "/optol/",
    balon: "/balon/",
    balonfurgon: "/balonfurgon/",
    clients: "/clients/",
    rayhistoryaction:"/rayshistory-actions/",
    DRIVER_PAYMENTS: {
        GET_ALL: "/driversalary/",
        GET_BY_DRIVER: "/driversalary/?driver=",
        CREATE: "/driversalary/",
        UPDATE: "/driversalary/",
        DELETE: "/driversalary/",
    },
    RAYS: {
        GET_ALL_RAYS: "/rays/",
        CREATE_RAYS: "/rays/",
        GET_RAY_DETAILS: "/rays/",
        UPDATE_RAY: "/rays/",
        DELETE_RAY: "/rays/",
        COMPLETE_RACE: "complete-race/",
        COMPLETE_CLIENT_RACE: "/rays-complete-client",
        COMPLETE_ALL_RAYS: "/rayshistory/",
        UPDATE_STATUS: "/rays-status",
        RETURN_FROM_HISTORY: "/rayshistory-actions",
        EXPORT_RAYS: "/rays/export/",
    }
};